name: CI

on:
  pull_request:
  workflow_dispatch:

env:
  macosGradleArgs: "-Dorg.gradle.jvmargs=-Xmx10g -Dfile.encoding=UTF-8 -XX:+UseParallelGC"
  ubuntuGradleArgs: "-Dorg.gradle.jvmargs=-Xmx5g -Dfile.encoding=UTF-8 -XX:+UseParallelGC"
  windowsGradleArgs: "-Dorg.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8 -XX:+UseParallelGC"

concurrency:
  group: ci-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:

  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: check out with token (used by forks)
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        if: github.event.pull_request.head.repo.full_name != github.repository

      - name: check out with PAT (used by main repo)
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        if: github.event.pull_request.head.repo.full_name == github.repository
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
        with:
          distribution: "zulu"
          java-version: "11"

      - name: detekt
        uses: gradle/gradle-build-action@4c39dd82cd5e1ec7c6fa0173bb41b4b6bb3b86ff # v3
        with:
          arguments: detektAll
          cache-read-only: false

      - name: KtLint format (used by main repo)
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: gradle/gradle-build-action@4c39dd82cd5e1ec7c6fa0173bb41b4b6bb3b86ff # v3
        with:
          arguments: ktlintFormat
          cache-read-only: false

      # If KtLint generated changes, commit and push those changes.
      - name: commit changes (used by main repo)
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5
        with:
          commit_message: Apply KtLint format
          commit_options: "--no-verify --signoff"

      - name: KtLint check (used by forks)
        if: github.event.pull_request.head.repo.full_name != github.repository
        uses: gradle/gradle-build-action@4c39dd82cd5e1ec7c6fa0173bb41b4b6bb3b86ff # v3
        with:
          arguments: ktlintCheck
          cache-read-only: false

      - name: Doks format (used by main repo)
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: gradle/gradle-build-action@4c39dd82cd5e1ec7c6fa0173bb41b4b6bb3b86ff # v3
        with:
          arguments: doks
          cache-read-only: false

      # If Doks generated changes, commit and push those changes.
      - name: commit changes (used by main repo)
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5
        with:
          commit_message: Apply Doks updates
          commit_options: "--no-verify --signoff"

      - name: Doks check (used by forks)
        if: github.event.pull_request.head.repo.full_name != github.repository
        uses: gradle/gradle-build-action@4c39dd82cd5e1ec7c6fa0173bb41b4b6bb3b86ff # v3
        with:
          arguments: doksCheck
          cache-read-only: false

  tests-macos:
    runs-on: ubuntu-latest

    steps:
      - name: check out with token
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Set up JDK
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
        with:
          distribution: "zulu"
          java-version: "11"

      - name: all tests
        uses: gradle/gradle-build-action@4c39dd82cd5e1ec7c6fa0173bb41b4b6bb3b86ff # v3
        with:
          arguments: test "${{ env.ubuntuGradleArgs }}"
          cache-read-only: false

      - name: Archive test results
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
        if: failure()
        with:
          name: test-results-ubuntu
          path: ./**/build/reports/tests/

      - name: Unit test results
        uses: mikepenz/action-junit-report@9379f0ccddcab154835d4e2487555ee79614fe95 # v4
        if: failure()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: "**/build/**/TEST-*.xml"
          check_name: Unit Test Results - ubuntu

  tests-windows:
    runs-on: windows-latest

    steps:
      - name: check out with token
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Set up JDK
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
        with:
          distribution: "zulu"
          java-version: "11"

      - name: all tests
        uses: gradle/gradle-build-action@4c39dd82cd5e1ec7c6fa0173bb41b4b6bb3b86ff # v3
        with:
          arguments: test "${{ env.windowsGradleArgs }}"
          cache-read-only: false

      - name: Archive test results
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
        if: failure()
        with:
          name: test-results-windows
          path: ./**/build/reports/tests/

      - name: Unit test results
        uses: mikepenz/action-junit-report@9379f0ccddcab154835d4e2487555ee79614fe95 # v4
        if: failure()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: "**/build/**/TEST-*.xml"
          check_name: Unit Test Results - Windows

  all-checks:
    if: always()
    runs-on: ubuntu-latest
    needs:
      - static-analysis
      - tests-macos
      - tests-windows

    steps:
      - name: require that all other jobs have passed
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
