name: Publish snapshot

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  gradleArgs: "-Dorg.gradle.jvmargs=-Xmx10g -Dfile.encoding=UTF-8 -XX:+UseParallelGC"

jobs:
  publish-snapshot:
    runs-on: macos-latest
    if: github.repository == 'RBusarow/ktrules'
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
        with:
          distribution: "zulu"
          java-version: "11"

      # break the publishing builds down a little into smaller steps
      # because gradle-build-action's caching is all-or-nothing.  If the full publish task
      # takes too long and times out, no cache is retained.

      - name: Compile Kotlin
        uses: gradle/gradle-build-action@66535aaf56f831b35e3a8481c9c99b665b84dd45 # v3
        with:
          arguments: compileKotlin "${{ env.gradleArgs }}"

      - name: Dokka & DokkaJavadoc
        uses: gradle/gradle-build-action@66535aaf56f831b35e3a8481c9c99b665b84dd45 # v3
        with:
          arguments: dokkaJavadoc "${{ env.gradleArgs }}"

      - name: Publish Snapshots
        uses: gradle/gradle-build-action@66535aaf56f831b35e3a8481c9c99b665b84dd45 # v3
        with:
          arguments: publish "${{ env.gradleArgs }}"
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
